/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMarcasRouteImport } from './routes/_authenticated/marcas'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedEtiquetasRouteImport } from './routes/_authenticated/etiquetas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos.index'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque.index'
import { Route as AuthenticatedProdutosNovoRouteImport } from './routes/_authenticated/produtos.novo'
import { Route as AuthenticatedProdutosIdRouteImport } from './routes/_authenticated/produtos.$id'
import { Route as AuthenticatedEstoqueMovimentacoesRouteImport } from './routes/_authenticated/estoque.movimentacoes'
import { Route as AuthenticatedEstoqueInventarioRouteImport } from './routes/_authenticated/estoque.inventario'
import { Route as AuthenticatedEstoqueEntradaRouteImport } from './routes/_authenticated/estoque.entrada'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarcasRoute = AuthenticatedMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtiquetasRoute = AuthenticatedEtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/estoque/',
    path: '/estoque/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosNovoRoute =
  AuthenticatedProdutosNovoRouteImport.update({
    id: '/produtos/novo',
    path: '/produtos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIdRoute = AuthenticatedProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueMovimentacoesRoute =
  AuthenticatedEstoqueMovimentacoesRouteImport.update({
    id: '/estoque/movimentacoes',
    path: '/estoque/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueInventarioRoute =
  AuthenticatedEstoqueInventarioRouteImport.update({
    id: '/estoque/inventario',
    path: '/estoque/inventario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueEntradaRoute =
  AuthenticatedEstoqueEntradaRouteImport.update({
    id: '/estoque/entrada',
    path: '/estoque/entrada',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/marcas': typeof AuthenticatedMarcasRoute
  '/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/produtos/': typeof AuthenticatedProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/marcas': typeof AuthenticatedMarcasRoute
  '/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/marcas': typeof AuthenticatedMarcasRoute
  '/_authenticated/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/_authenticated/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/_authenticated/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/_authenticated/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/_authenticated/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/categorias'
    | '/dashboard'
    | '/etiquetas'
    | '/fornecedores'
    | '/marcas'
    | '/estoque/entrada'
    | '/estoque/inventario'
    | '/estoque/movimentacoes'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/estoque/'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/categorias'
    | '/dashboard'
    | '/etiquetas'
    | '/fornecedores'
    | '/marcas'
    | '/estoque/entrada'
    | '/estoque/inventario'
    | '/estoque/movimentacoes'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/estoque'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/categorias'
    | '/_authenticated/dashboard'
    | '/_authenticated/etiquetas'
    | '/_authenticated/fornecedores'
    | '/_authenticated/marcas'
    | '/_authenticated/estoque/entrada'
    | '/_authenticated/estoque/inventario'
    | '/_authenticated/estoque/movimentacoes'
    | '/_authenticated/produtos/$id'
    | '/_authenticated/produtos/novo'
    | '/_authenticated/estoque/'
    | '/_authenticated/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marcas': {
      id: '/_authenticated/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof AuthenticatedMarcasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiquetas': {
      id: '/_authenticated/etiquetas'
      path: '/etiquetas'
      fullPath: '/etiquetas'
      preLoaderRoute: typeof AuthenticatedEtiquetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/novo': {
      id: '/_authenticated/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AuthenticatedProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/$id': {
      id: '/_authenticated/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof AuthenticatedProdutosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/movimentacoes': {
      id: '/_authenticated/estoque/movimentacoes'
      path: '/estoque/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/inventario': {
      id: '/_authenticated/estoque/inventario'
      path: '/estoque/inventario'
      fullPath: '/estoque/inventario'
      preLoaderRoute: typeof AuthenticatedEstoqueInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/entrada': {
      id: '/_authenticated/estoque/entrada'
      path: '/estoque/entrada'
      fullPath: '/estoque/entrada'
      preLoaderRoute: typeof AuthenticatedEstoqueEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEtiquetasRoute: typeof AuthenticatedEtiquetasRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedMarcasRoute: typeof AuthenticatedMarcasRoute
  AuthenticatedEstoqueEntradaRoute: typeof AuthenticatedEstoqueEntradaRoute
  AuthenticatedEstoqueInventarioRoute: typeof AuthenticatedEstoqueInventarioRoute
  AuthenticatedEstoqueMovimentacoesRoute: typeof AuthenticatedEstoqueMovimentacoesRoute
  AuthenticatedProdutosIdRoute: typeof AuthenticatedProdutosIdRoute
  AuthenticatedProdutosNovoRoute: typeof AuthenticatedProdutosNovoRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEtiquetasRoute: AuthenticatedEtiquetasRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedMarcasRoute: AuthenticatedMarcasRoute,
  AuthenticatedEstoqueEntradaRoute: AuthenticatedEstoqueEntradaRoute,
  AuthenticatedEstoqueInventarioRoute: AuthenticatedEstoqueInventarioRoute,
  AuthenticatedEstoqueMovimentacoesRoute:
    AuthenticatedEstoqueMovimentacoesRoute,
  AuthenticatedProdutosIdRoute: AuthenticatedProdutosIdRoute,
  AuthenticatedProdutosNovoRoute: AuthenticatedProdutosNovoRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
