/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedMarcasRouteImport } from './routes/_authenticated/marcas'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedEtiquetasRouteImport } from './routes/_authenticated/etiquetas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedCargosRouteImport } from './routes/_authenticated/cargos'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedVendasIndexRouteImport } from './routes/_authenticated/vendas.index'
import { Route as AuthenticatedTrocasIndexRouteImport } from './routes/_authenticated/trocas.index'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos.index'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedVendasIdRouteImport } from './routes/_authenticated/vendas.$id'
import { Route as AuthenticatedTrocasValesRouteImport } from './routes/_authenticated/trocas.vales'
import { Route as AuthenticatedTrocasNovaRouteImport } from './routes/_authenticated/trocas.nova'
import { Route as AuthenticatedTrocasCreditosRouteImport } from './routes/_authenticated/trocas.creditos'
import { Route as AuthenticatedTrocasIdRouteImport } from './routes/_authenticated/trocas.$id'
import { Route as AuthenticatedRelatoriosTrocasRouteImport } from './routes/_authenticated/relatorios.trocas'
import { Route as AuthenticatedProdutosNovoRouteImport } from './routes/_authenticated/produtos.novo'
import { Route as AuthenticatedProdutosIdRouteImport } from './routes/_authenticated/produtos.$id'
import { Route as AuthenticatedEstoqueMovimentacoesRouteImport } from './routes/_authenticated/estoque.movimentacoes'
import { Route as AuthenticatedEstoqueInventarioRouteImport } from './routes/_authenticated/estoque.inventario'
import { Route as AuthenticatedEstoqueEntradaRouteImport } from './routes/_authenticated/estoque.entrada'
import { Route as AuthenticatedConfiguracoesTrocasRouteImport } from './routes/_authenticated/configuracoes.trocas'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedEstoqueRecebimentosIndexRouteImport } from './routes/_authenticated/estoque.recebimentos.index'
import { Route as AuthenticatedEtiquetasLotesIdRouteImport } from './routes/_authenticated/etiquetas.lotes.$id'
import { Route as AuthenticatedEstoqueRecebimentosNovoRouteImport } from './routes/_authenticated/estoque.recebimentos.novo'
import { Route as AuthenticatedEstoqueRecebimentosIdRouteImport } from './routes/_authenticated/estoque.recebimentos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarcasRoute = AuthenticatedMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtiquetasRoute = AuthenticatedEtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCargosRoute = AuthenticatedCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasIndexRoute =
  AuthenticatedVendasIndexRouteImport.update({
    id: '/vendas/',
    path: '/vendas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrocasIndexRoute =
  AuthenticatedTrocasIndexRouteImport.update({
    id: '/trocas/',
    path: '/trocas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/estoque/',
    path: '/estoque/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasIdRoute = AuthenticatedVendasIdRouteImport.update({
  id: '/vendas/$id',
  path: '/vendas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocasValesRoute =
  AuthenticatedTrocasValesRouteImport.update({
    id: '/trocas/vales',
    path: '/trocas/vales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrocasNovaRoute = AuthenticatedTrocasNovaRouteImport.update({
  id: '/trocas/nova',
  path: '/trocas/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocasCreditosRoute =
  AuthenticatedTrocasCreditosRouteImport.update({
    id: '/trocas/creditos',
    path: '/trocas/creditos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrocasIdRoute = AuthenticatedTrocasIdRouteImport.update({
  id: '/trocas/$id',
  path: '/trocas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosTrocasRoute =
  AuthenticatedRelatoriosTrocasRouteImport.update({
    id: '/relatorios/trocas',
    path: '/relatorios/trocas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosNovoRoute =
  AuthenticatedProdutosNovoRouteImport.update({
    id: '/produtos/novo',
    path: '/produtos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIdRoute = AuthenticatedProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueMovimentacoesRoute =
  AuthenticatedEstoqueMovimentacoesRouteImport.update({
    id: '/estoque/movimentacoes',
    path: '/estoque/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueInventarioRoute =
  AuthenticatedEstoqueInventarioRouteImport.update({
    id: '/estoque/inventario',
    path: '/estoque/inventario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueEntradaRoute =
  AuthenticatedEstoqueEntradaRouteImport.update({
    id: '/estoque/entrada',
    path: '/estoque/entrada',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesTrocasRoute =
  AuthenticatedConfiguracoesTrocasRouteImport.update({
    id: '/trocas',
    path: '/trocas',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRecebimentosIndexRoute =
  AuthenticatedEstoqueRecebimentosIndexRouteImport.update({
    id: '/estoque/recebimentos/',
    path: '/estoque/recebimentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtiquetasLotesIdRoute =
  AuthenticatedEtiquetasLotesIdRouteImport.update({
    id: '/lotes/$id',
    path: '/lotes/$id',
    getParentRoute: () => AuthenticatedEtiquetasRoute,
  } as any)
const AuthenticatedEstoqueRecebimentosNovoRoute =
  AuthenticatedEstoqueRecebimentosNovoRouteImport.update({
    id: '/estoque/recebimentos/novo',
    path: '/estoque/recebimentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRecebimentosIdRoute =
  AuthenticatedEstoqueRecebimentosIdRouteImport.update({
    id: '/estoque/recebimentos/$id',
    path: '/estoque/recebimentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etiquetas': typeof AuthenticatedEtiquetasRouteWithChildren
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/marcas': typeof AuthenticatedMarcasRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/configuracoes/trocas': typeof AuthenticatedConfiguracoesTrocasRoute
  '/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/relatorios/trocas': typeof AuthenticatedRelatoriosTrocasRoute
  '/trocas/$id': typeof AuthenticatedTrocasIdRoute
  '/trocas/creditos': typeof AuthenticatedTrocasCreditosRoute
  '/trocas/nova': typeof AuthenticatedTrocasNovaRoute
  '/trocas/vales': typeof AuthenticatedTrocasValesRoute
  '/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/trocas/': typeof AuthenticatedTrocasIndexRoute
  '/vendas/': typeof AuthenticatedVendasIndexRoute
  '/estoque/recebimentos/$id': typeof AuthenticatedEstoqueRecebimentosIdRoute
  '/estoque/recebimentos/novo': typeof AuthenticatedEstoqueRecebimentosNovoRoute
  '/etiquetas/lotes/$id': typeof AuthenticatedEtiquetasLotesIdRoute
  '/estoque/recebimentos/': typeof AuthenticatedEstoqueRecebimentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etiquetas': typeof AuthenticatedEtiquetasRouteWithChildren
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/marcas': typeof AuthenticatedMarcasRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/configuracoes/trocas': typeof AuthenticatedConfiguracoesTrocasRoute
  '/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/relatorios/trocas': typeof AuthenticatedRelatoriosTrocasRoute
  '/trocas/$id': typeof AuthenticatedTrocasIdRoute
  '/trocas/creditos': typeof AuthenticatedTrocasCreditosRoute
  '/trocas/nova': typeof AuthenticatedTrocasNovaRoute
  '/trocas/vales': typeof AuthenticatedTrocasValesRoute
  '/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/trocas': typeof AuthenticatedTrocasIndexRoute
  '/vendas': typeof AuthenticatedVendasIndexRoute
  '/estoque/recebimentos/$id': typeof AuthenticatedEstoqueRecebimentosIdRoute
  '/estoque/recebimentos/novo': typeof AuthenticatedEstoqueRecebimentosNovoRoute
  '/etiquetas/lotes/$id': typeof AuthenticatedEtiquetasLotesIdRoute
  '/estoque/recebimentos': typeof AuthenticatedEstoqueRecebimentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/cargos': typeof AuthenticatedCargosRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/etiquetas': typeof AuthenticatedEtiquetasRouteWithChildren
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/marcas': typeof AuthenticatedMarcasRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/configuracoes/trocas': typeof AuthenticatedConfiguracoesTrocasRoute
  '/_authenticated/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/_authenticated/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/_authenticated/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/_authenticated/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/_authenticated/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/_authenticated/relatorios/trocas': typeof AuthenticatedRelatoriosTrocasRoute
  '/_authenticated/trocas/$id': typeof AuthenticatedTrocasIdRoute
  '/_authenticated/trocas/creditos': typeof AuthenticatedTrocasCreditosRoute
  '/_authenticated/trocas/nova': typeof AuthenticatedTrocasNovaRoute
  '/_authenticated/trocas/vales': typeof AuthenticatedTrocasValesRoute
  '/_authenticated/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/_authenticated/trocas/': typeof AuthenticatedTrocasIndexRoute
  '/_authenticated/vendas/': typeof AuthenticatedVendasIndexRoute
  '/_authenticated/estoque/recebimentos/$id': typeof AuthenticatedEstoqueRecebimentosIdRoute
  '/_authenticated/estoque/recebimentos/novo': typeof AuthenticatedEstoqueRecebimentosNovoRoute
  '/_authenticated/etiquetas/lotes/$id': typeof AuthenticatedEtiquetasLotesIdRoute
  '/_authenticated/estoque/recebimentos/': typeof AuthenticatedEstoqueRecebimentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/sitemap.xml'
    | '/auditoria'
    | '/caixa'
    | '/cargos'
    | '/categorias'
    | '/configuracoes'
    | '/dashboard'
    | '/etiquetas'
    | '/fornecedores'
    | '/funcionarios'
    | '/marcas'
    | '/pdv'
    | '/clientes/$id'
    | '/configuracoes/trocas'
    | '/estoque/entrada'
    | '/estoque/inventario'
    | '/estoque/movimentacoes'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/relatorios/trocas'
    | '/trocas/$id'
    | '/trocas/creditos'
    | '/trocas/nova'
    | '/trocas/vales'
    | '/vendas/$id'
    | '/clientes/'
    | '/estoque/'
    | '/produtos/'
    | '/trocas/'
    | '/vendas/'
    | '/estoque/recebimentos/$id'
    | '/estoque/recebimentos/novo'
    | '/etiquetas/lotes/$id'
    | '/estoque/recebimentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/sitemap.xml'
    | '/auditoria'
    | '/caixa'
    | '/cargos'
    | '/categorias'
    | '/configuracoes'
    | '/dashboard'
    | '/etiquetas'
    | '/fornecedores'
    | '/funcionarios'
    | '/marcas'
    | '/pdv'
    | '/clientes/$id'
    | '/configuracoes/trocas'
    | '/estoque/entrada'
    | '/estoque/inventario'
    | '/estoque/movimentacoes'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/relatorios/trocas'
    | '/trocas/$id'
    | '/trocas/creditos'
    | '/trocas/nova'
    | '/trocas/vales'
    | '/vendas/$id'
    | '/clientes'
    | '/estoque'
    | '/produtos'
    | '/trocas'
    | '/vendas'
    | '/estoque/recebimentos/$id'
    | '/estoque/recebimentos/novo'
    | '/etiquetas/lotes/$id'
    | '/estoque/recebimentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/sitemap.xml'
    | '/_authenticated/auditoria'
    | '/_authenticated/caixa'
    | '/_authenticated/cargos'
    | '/_authenticated/categorias'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/etiquetas'
    | '/_authenticated/fornecedores'
    | '/_authenticated/funcionarios'
    | '/_authenticated/marcas'
    | '/_authenticated/pdv'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/configuracoes/trocas'
    | '/_authenticated/estoque/entrada'
    | '/_authenticated/estoque/inventario'
    | '/_authenticated/estoque/movimentacoes'
    | '/_authenticated/produtos/$id'
    | '/_authenticated/produtos/novo'
    | '/_authenticated/relatorios/trocas'
    | '/_authenticated/trocas/$id'
    | '/_authenticated/trocas/creditos'
    | '/_authenticated/trocas/nova'
    | '/_authenticated/trocas/vales'
    | '/_authenticated/vendas/$id'
    | '/_authenticated/clientes/'
    | '/_authenticated/estoque/'
    | '/_authenticated/produtos/'
    | '/_authenticated/trocas/'
    | '/_authenticated/vendas/'
    | '/_authenticated/estoque/recebimentos/$id'
    | '/_authenticated/estoque/recebimentos/novo'
    | '/_authenticated/etiquetas/lotes/$id'
    | '/_authenticated/estoque/recebimentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marcas': {
      id: '/_authenticated/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof AuthenticatedMarcasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiquetas': {
      id: '/_authenticated/etiquetas'
      path: '/etiquetas'
      fullPath: '/etiquetas'
      preLoaderRoute: typeof AuthenticatedEtiquetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cargos': {
      id: '/_authenticated/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof AuthenticatedCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/': {
      id: '/_authenticated/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AuthenticatedVendasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas/': {
      id: '/_authenticated/trocas/'
      path: '/trocas'
      fullPath: '/trocas/'
      preLoaderRoute: typeof AuthenticatedTrocasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/$id': {
      id: '/_authenticated/vendas/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof AuthenticatedVendasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas/vales': {
      id: '/_authenticated/trocas/vales'
      path: '/trocas/vales'
      fullPath: '/trocas/vales'
      preLoaderRoute: typeof AuthenticatedTrocasValesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas/nova': {
      id: '/_authenticated/trocas/nova'
      path: '/trocas/nova'
      fullPath: '/trocas/nova'
      preLoaderRoute: typeof AuthenticatedTrocasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas/creditos': {
      id: '/_authenticated/trocas/creditos'
      path: '/trocas/creditos'
      fullPath: '/trocas/creditos'
      preLoaderRoute: typeof AuthenticatedTrocasCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas/$id': {
      id: '/_authenticated/trocas/$id'
      path: '/trocas/$id'
      fullPath: '/trocas/$id'
      preLoaderRoute: typeof AuthenticatedTrocasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/trocas': {
      id: '/_authenticated/relatorios/trocas'
      path: '/relatorios/trocas'
      fullPath: '/relatorios/trocas'
      preLoaderRoute: typeof AuthenticatedRelatoriosTrocasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/novo': {
      id: '/_authenticated/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AuthenticatedProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/$id': {
      id: '/_authenticated/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof AuthenticatedProdutosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/movimentacoes': {
      id: '/_authenticated/estoque/movimentacoes'
      path: '/estoque/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/inventario': {
      id: '/_authenticated/estoque/inventario'
      path: '/estoque/inventario'
      fullPath: '/estoque/inventario'
      preLoaderRoute: typeof AuthenticatedEstoqueInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/entrada': {
      id: '/_authenticated/estoque/entrada'
      path: '/estoque/entrada'
      fullPath: '/estoque/entrada'
      preLoaderRoute: typeof AuthenticatedEstoqueEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/trocas': {
      id: '/_authenticated/configuracoes/trocas'
      path: '/trocas'
      fullPath: '/configuracoes/trocas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesTrocasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/recebimentos/': {
      id: '/_authenticated/estoque/recebimentos/'
      path: '/estoque/recebimentos'
      fullPath: '/estoque/recebimentos/'
      preLoaderRoute: typeof AuthenticatedEstoqueRecebimentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiquetas/lotes/$id': {
      id: '/_authenticated/etiquetas/lotes/$id'
      path: '/lotes/$id'
      fullPath: '/etiquetas/lotes/$id'
      preLoaderRoute: typeof AuthenticatedEtiquetasLotesIdRouteImport
      parentRoute: typeof AuthenticatedEtiquetasRoute
    }
    '/_authenticated/estoque/recebimentos/novo': {
      id: '/_authenticated/estoque/recebimentos/novo'
      path: '/estoque/recebimentos/novo'
      fullPath: '/estoque/recebimentos/novo'
      preLoaderRoute: typeof AuthenticatedEstoqueRecebimentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/recebimentos/$id': {
      id: '/_authenticated/estoque/recebimentos/$id'
      path: '/estoque/recebimentos/$id'
      fullPath: '/estoque/recebimentos/$id'
      preLoaderRoute: typeof AuthenticatedEstoqueRecebimentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesTrocasRoute: typeof AuthenticatedConfiguracoesTrocasRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesTrocasRoute:
      AuthenticatedConfiguracoesTrocasRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedEtiquetasRouteChildren {
  AuthenticatedEtiquetasLotesIdRoute: typeof AuthenticatedEtiquetasLotesIdRoute
}

const AuthenticatedEtiquetasRouteChildren: AuthenticatedEtiquetasRouteChildren =
  {
    AuthenticatedEtiquetasLotesIdRoute: AuthenticatedEtiquetasLotesIdRoute,
  }

const AuthenticatedEtiquetasRouteWithChildren =
  AuthenticatedEtiquetasRoute._addFileChildren(
    AuthenticatedEtiquetasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCargosRoute: typeof AuthenticatedCargosRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEtiquetasRoute: typeof AuthenticatedEtiquetasRouteWithChildren
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedMarcasRoute: typeof AuthenticatedMarcasRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedEstoqueEntradaRoute: typeof AuthenticatedEstoqueEntradaRoute
  AuthenticatedEstoqueInventarioRoute: typeof AuthenticatedEstoqueInventarioRoute
  AuthenticatedEstoqueMovimentacoesRoute: typeof AuthenticatedEstoqueMovimentacoesRoute
  AuthenticatedProdutosIdRoute: typeof AuthenticatedProdutosIdRoute
  AuthenticatedProdutosNovoRoute: typeof AuthenticatedProdutosNovoRoute
  AuthenticatedRelatoriosTrocasRoute: typeof AuthenticatedRelatoriosTrocasRoute
  AuthenticatedTrocasIdRoute: typeof AuthenticatedTrocasIdRoute
  AuthenticatedTrocasCreditosRoute: typeof AuthenticatedTrocasCreditosRoute
  AuthenticatedTrocasNovaRoute: typeof AuthenticatedTrocasNovaRoute
  AuthenticatedTrocasValesRoute: typeof AuthenticatedTrocasValesRoute
  AuthenticatedVendasIdRoute: typeof AuthenticatedVendasIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
  AuthenticatedTrocasIndexRoute: typeof AuthenticatedTrocasIndexRoute
  AuthenticatedVendasIndexRoute: typeof AuthenticatedVendasIndexRoute
  AuthenticatedEstoqueRecebimentosIdRoute: typeof AuthenticatedEstoqueRecebimentosIdRoute
  AuthenticatedEstoqueRecebimentosNovoRoute: typeof AuthenticatedEstoqueRecebimentosNovoRoute
  AuthenticatedEstoqueRecebimentosIndexRoute: typeof AuthenticatedEstoqueRecebimentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCargosRoute: AuthenticatedCargosRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEtiquetasRoute: AuthenticatedEtiquetasRouteWithChildren,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedMarcasRoute: AuthenticatedMarcasRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedEstoqueEntradaRoute: AuthenticatedEstoqueEntradaRoute,
  AuthenticatedEstoqueInventarioRoute: AuthenticatedEstoqueInventarioRoute,
  AuthenticatedEstoqueMovimentacoesRoute:
    AuthenticatedEstoqueMovimentacoesRoute,
  AuthenticatedProdutosIdRoute: AuthenticatedProdutosIdRoute,
  AuthenticatedProdutosNovoRoute: AuthenticatedProdutosNovoRoute,
  AuthenticatedRelatoriosTrocasRoute: AuthenticatedRelatoriosTrocasRoute,
  AuthenticatedTrocasIdRoute: AuthenticatedTrocasIdRoute,
  AuthenticatedTrocasCreditosRoute: AuthenticatedTrocasCreditosRoute,
  AuthenticatedTrocasNovaRoute: AuthenticatedTrocasNovaRoute,
  AuthenticatedTrocasValesRoute: AuthenticatedTrocasValesRoute,
  AuthenticatedVendasIdRoute: AuthenticatedVendasIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
  AuthenticatedTrocasIndexRoute: AuthenticatedTrocasIndexRoute,
  AuthenticatedVendasIndexRoute: AuthenticatedVendasIndexRoute,
  AuthenticatedEstoqueRecebimentosIdRoute:
    AuthenticatedEstoqueRecebimentosIdRoute,
  AuthenticatedEstoqueRecebimentosNovoRoute:
    AuthenticatedEstoqueRecebimentosNovoRoute,
  AuthenticatedEstoqueRecebimentosIndexRoute:
    AuthenticatedEstoqueRecebimentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
